defaults:
  - data: default
  - model: distilbert
  - mlflow: default
  - _self_

seed: 42

trainer:
  accelerator: cpu
  devices: 1
  max_epochs: 1
  log_every_n_steps: 10
  precision: 16-mixed

output_dir: outputs
